// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class RedditCatsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
 
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void fUNJOINBUTTONEXISTS() {
    driver.get("https://www.reddit.com/");
    driver.manage().window().setSize(new Dimension(1198, 699));
    driver.findElement(By.id("header-search-bar")).click();
    driver.findElement(By.id("header-search-bar")).sendKeys("cats");
    driver.findElement(By.cssSelector(".\\_20OHBqoDD71_8fv7tuG6u6:nth-child(1) .\\_17mZueOafzj0Dlja0Wc9os")).click();
    js.executeScript("window.scrollTo(0,102)");
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_3dZnYgFFpifT-M_Vs2FAq6:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_2RkQc9Gtsq3cPQNZLYv4zc"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,203)");
    {
      WebElement element = driver.findElement(By.linkText("Create Post"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,102)");
    assertThat(driver.findElement(By.cssSelector(".\\_2CLbCoThTVSANDpeJGlI6a")).getText(), is("Join"));
  }
  @Test
  public void fUNRULE3() {
    driver.get("https://www.reddit.com/");
    driver.findElement(By.id("header-search-bar")).click();
    driver.findElement(By.id("header-search-bar")).sendKeys("cats");
    driver.findElement(By.cssSelector(".\\_20OHBqoDD71_8fv7tuG6u6:nth-child(1) .\\_17mZueOafzj0Dlja0Wc9os")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_20OHBqoDD71_8fv7tuG6u6:nth-child(1) .\\_17mZueOafzj0Dlja0Wc9os"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    assertThat(driver.findElement(By.cssSelector(".\\_8ZLJI1-ZiP7pHJ_yO1L4Z:nth-child(3) .tbIApBd2DM_drfZQJjIum")).getText(), is("No NSFW, animal abuse, or cruelty"));
  }
  @Test
  public void fUNRULES11ITEMS() {
    driver.get("https://www.reddit.com/");
    driver.findElement(By.id("header-search-bar")).click();
    driver.findElement(By.id("header-search-bar")).sendKeys("cats");
    driver.findElement(By.cssSelector(".\\_20OHBqoDD71_8fv7tuG6u6:nth-child(2) .\\_17mZueOafzj0Dlja0Wc9os")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_2RkQc9Gtsq3cPQNZLYv4zc"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,200)");
    {
      WebElement element = driver.findElement(By.id("USER_DROPDOWN_ID"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".\\_8ZLJI1-ZiP7pHJ_yO1L4Z:nth-child(1)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".\\_8ZLJI1-ZiP7pHJ_yO1L4Z:nth-child(2)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".\\_8ZLJI1-ZiP7pHJ_yO1L4Z:nth-child(3)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".\\_8ZLJI1-ZiP7pHJ_yO1L4Z:nth-child(4)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".\\_8ZLJI1-ZiP7pHJ_yO1L4Z:nth-child(5)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".\\_8ZLJI1-ZiP7pHJ_yO1L4Z:nth-child(6)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".\\_8ZLJI1-ZiP7pHJ_yO1L4Z:nth-child(7)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".\\_8ZLJI1-ZiP7pHJ_yO1L4Z:nth-child(8)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".\\_8ZLJI1-ZiP7pHJ_yO1L4Z:nth-child(9)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".\\_8ZLJI1-ZiP7pHJ_yO1L4Z:nth-child(10)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".\\_8ZLJI1-ZiP7pHJ_yO1L4Z:nth-child(11)"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void fUNSEARCHSMELLYCAT() {
    driver.get("https://www.reddit.com/");
    driver.findElement(By.id("header-search-bar")).click();
    driver.findElement(By.id("header-search-bar")).sendKeys("smelly cats");
    driver.findElement(By.id("header-search-bar")).sendKeys(Keys.ENTER);
    assertThat(driver.findElement(By.cssSelector(".\\_3j9XjJayuKq7dJ8huVnCuS")).getText(), is("smelly cats"));
  }
  @Test
  public void fUNSIGNUPLINK() {
    driver.get("https://www.reddit.comr/cats/");
    driver.findElement(By.id("header-search-bar")).click();
    driver.findElement(By.id("header-search-bar")).sendKeys("cats");
    driver.findElement(By.cssSelector(".\\_20OHBqoDD71_8fv7tuG6u6:nth-child(1) .\\_17mZueOafzj0Dlja0Wc9os")).click();
    {
      WebElement element = driver.findElement(By.linkText("Sign Up"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("Sign Up"));
      String attribute = element.getAttribute("href");
      vars.put("val", attribute);
    }
    assertEquals(vars.get("val").toString(), "https://www.reddit.com/register/?dest=https%3A%2F%2Fwww.reddit.com%2Fr%2Fcats%2F");
  }
  @Test
  public void tESTTITLE() {
    driver.get("https://www.reddit.com/r/cats/");
    driver.findElement(By.id("header-search-bar")).click();
    driver.findElement(By.id("header-search-bar")).sendKeys("cats");
    driver.findElement(By.cssSelector(".\\_20OHBqoDD71_8fv7tuG6u6:nth-child(1) .\\_17mZueOafzj0Dlja0Wc9os")).click();
    assertThat(driver.findElement(By.cssSelector(".\\_2yYPPW47QxD4lFQTKpfpLQ")).getText(), is("Cats"));
  }
}
